# home_dir should be the location of pvr-generalization
root_dir: '/bd_byta6000i0/users/jhu/pvr-generalization'
epoch: 50
device: 'cuda'
frame_stack: 3
encoder_name: ???
log_dir: 'pvr-imitation/logs'
specific_log_dir: null
task_name: ???
env:
    root_dir: ${root_dir}
    task_name: ${task_name}
    config_file: 'pvr-imitation/env_cfgs/${task_name}.yaml'
eval:
    eval_freq: 10
    eval_episodes: 10
    max_length: 200
    save_results: True
    data_cfg:
      # The image types that will be recorded
      images:
        rgb: True
        depth: False
        mask: False
        point_cloud: False
      # The cameras that we will be enabled
      cameras:
        left_shoulder: False
        right_shoulder: False
        overhead: False
        wrist: False
        front: True

dataset:
  root_dir: ${root_dir}
  data_folder: 'rlbench_data/${task_name}/variation0/episodes'
  img_type: 'front_rgb'
  encoder_name: ${encoder_name}
  batch_size: 256
  frame_stack: ${frame_stack}
  device: ${device}

policy:
  root_dir: ${root_dir}
  device: ${device}
  input_dim: ???
  hidden_dim: [256, 256]
  action_dim: ???s
  encoder_name: ${encoder_name}
  frame_stack: ${frame_stack}