exp_id: rvt2
tasks: stack_cups,insert_onto_square_peg,open_drawer,basketball_in_hoop,close_box,empty_dishwasher,meat_on_grill,place_wine_at_rack_location,put_money_in_safe,reach_and_drag,setup_chess,slide_block_to_target,turn_oven_on,close_laptop_lid,scoop_with_spatula,get_ice_from_fridge,straighten_rope
bs: 16
num_workers: 8
epochs: 10
sample_distribution_mode: task_uniform
verbose: False
resume: ""
num_episodes: 100
peract:
  lr: 1.25e-5
  warmup_steps: 2000
  optimizer_type: lamb
  lr_cos_dec: True
  transform_augmentation_xyz: [0.125, 0.125, 0.125]
  transform_augmentation_rpy: [0.0, 0.0, 45.0]
  amp: True
  bnb: True
  lambda_weight_l2: 1e-4
rvt:
  place_with_mean: False
  img_aug: 0.0
